
services:
  app:
    build: .
    container_name: kilt-core
    ports:
      - "3000:3000"
    env_file:
      - .env
      - .env.dev 
    environment:
      - NODE_ENV=development 
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
